before_install:
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - git checkout 0.6.1
 - ./autogen.sh
 - ./configure && make check
 - sudo make install
 - cd ..
 - git clone git://github.com/zeromq/zeromq3-x.git
 - cd zeromq3-x
 - ./autogen.sh
 - ./configure && make check
 - sudo make install
 - sudo ldconfig
 - cd ..
 - cmake .
install: mvn install --quiet -DskipTests=true -Dgpg.skip=true
language: java
script: mvn compile clojure:test
jdk:
  - openjdk7
  - openjdk6
