before_install:
 - git clone git://github.com/zeromq/zeromq3-x.git
 - cd zeromq3-x
 - ./autogen.sh
 - ./configure && make check
 - sudo make install
 - sudo ldconfig
 - cd ..
install: mvn install --quiet -DskipTests=true -Dgpg.skip=true
language: java
script: mvn clojure:test
jdk:
  - openjdk7
  - openjdk6
